/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2_201602598;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector
 */
public class Pantalla extends javax.swing.JFrame {
private DefaultTableModel modelo;
private String ruta;
private String[] columnas;
//private String[] server;
//int contadorserver;
Servidor servidor;
Personas persona;
//Dibujo_Server dibujoserver;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        ruta="";
        this.setLocationRelativeTo(null);
        columnas=new String[] {"Accion","NoServidor","Siguiente","X","Y","Alto","Ancho","TasaLlegada",
        "Tiempo","Tamaño","IdProducto","Nombre","Descripcion","Linea","Cantidad"};
        modelo=new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);
      //  server=new String[500];
        //contadorserver=0;
        servidor=new Servidor();
        persona=new Personas();
        /*modelo.addColumn("Accion");
        modelo.addColumn("NoServidor");
        modelo.addColumn("Siguiente");
        modelo.addColumn("X");
        modelo.addColumn("Y");
        modelo.addColumn("Alto");
        modelo.addColumn("Ancho");
        modelo.addColumn("Tasa Llegada");
        modelo.addColumn("Tiempo");
        modelo.addColumn("Tamaño");
        modelo.addColumn("idProducto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Linea");
        modelo.addColumn("Cantidad");*/
        this.tabla.setModel(modelo);
    }
    
    public void limpiarTabla(){
        int cantidadfilas=tabla.getRowCount();
        for(int i=cantidadfilas-1;i>=0;i--){
            modelo.removeRow(i);
        }
    }
    
    public void Llenar(String tipo,String[] datos){
        
        if(tipo.equalsIgnoreCase("Servidores")){
           servidor.setServer(datos[1],datos[2],datos[3],datos[4],datos[5],datos[6],datos[7]);
           System.out.println(Arrays.toString(datos));
           }else if(tipo.equalsIgnoreCase("Personas")){
             persona.setPersonas(datos[3], datos[4], datos[7], datos[8], datos[9]);
             
           }
        
    }
    
   /* public void setServer(String noserver,String siguiente,String x,String y,String alto,String ancho,
            String tiempo){
        server[contadorserver]=noserver+";"+siguiente+";"+x+";"+y+";"+alto+";"+ancho+";"+tiempo;
        contadorserver++;
    }*/
    
    /*public String[] obServer(){
    return server;
}*/
   /* public String obServerpo(int i){
        return server[i];
    }*/
    
   /* public int lonserver(){
        return server.length;
    }*/
    
    public String obRuta(){
        return ruta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btnabrir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnguardarcomo = new javax.swing.JButton();
        btnplay = new javax.swing.JButton();
        btnstop = new javax.swing.JButton();
        btnresultados = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Texto = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        paneldi = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnabrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrir-el-archivo-icono-8581-128.png"))); // NOI18N
        btnabrir.setToolTipText("Abrir");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });
        jPanel1.add(btnabrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, 50));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, 50));

        btnguardarcomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarcomo.png"))); // NOI18N
        btnguardarcomo.setToolTipText("Guardar Como");
        btnguardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarcomoActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardarcomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 70, 50));

        btnplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        btnplay.setToolTipText("Play");
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 70, 50));

        btnstop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stop.png"))); // NOI18N
        btnstop.setToolTipText("Stop");
        jPanel1.add(btnstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 70, 50));

        btnresultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resultados.png"))); // NOI18N
        btnresultados.setToolTipText("Resultados");
        jPanel1.add(btnresultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 70, 50));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnsalir.setToolTipText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 40, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 80));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Texto.setViewportView(tabla);

        jTabbedPane2.addTab("Solo lectura", Texto);
        jTabbedPane2.addTab("tab2", paneldi);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 340));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
        // TODO add your handling code here:
        
        //FILECHOOSER
        limpiarTabla();
        try{
        
            int resultado=fc.showOpenDialog(this);
            if(resultado==JFileChooser.CANCEL_OPTION){
                return;
            }else{
            
                ruta=fc.getSelectedFile().getAbsolutePath();
                FileReader archivo=new FileReader(ruta);
                BufferedReader bfr=new BufferedReader(archivo);
                String linea="";

                while(linea!=null){
                    linea=bfr.readLine();
                    if(linea!=null){
                   String aux[]=linea.split(";");
                   modelo.addRow(aux);
                   Llenar(aux[0],aux);
                   }
                }
                modelo.removeRow(0);
                archivo.close();
                }
    }catch(Exception e){
            e.printStackTrace();
            
        }
        
    }//GEN-LAST:event_btnabrirActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    try {
        // TODO add your handling code here:
        
        
            for(int as=0;as<servidor.oblong();as++){
                servidor.setServer(as);
            }
            servidor.reiniciarcont();
        
        
        String fila="";//
        String auxi="";
        FileWriter rutasave=new FileWriter(obRuta());
        BufferedWriter escribir=new BufferedWriter(rutasave);
        for(int w=0;w<columnas.length;w++){
            escribir.write(columnas[w]+";");
        }
        escribir.newLine();
        for(int i=0;i<tabla.getRowCount();i++){
            for(int j=0;j<tabla.getColumnCount();j++){
                 Object auxi2=tabla.getValueAt(i,j);
                if(auxi2!=null){
                    auxi=(String)auxi2; 
                    escribir.write(auxi+";");
                    fila=fila+auxi+";";//
                 }else{
                    escribir.write(";");
                   fila=fila+";";//
                }
                
              
            }
            String[] coo=fila.split(";");//
            Llenar(coo[0],coo);//
            fila="";//HASTA ACA
            escribir.newLine();
        }
        escribir.close();
        rutasave.close();
        JOptionPane.showMessageDialog(null, "Guardado exitosamente");
    } catch (IOException ex) {
        Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        //GUARDAR
        
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnguardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarcomoActionPerformed
        // TODO add your handling code here:
        //Guardar Como
        int resultado=fc.showSaveDialog(this);
        if(resultado==JFileChooser.CANCEL_OPTION){
            return;
        }else{
            File archivo=fc.getSelectedFile();
            try {
                FileWriter esc=new FileWriter(archivo);
                BufferedWriter bf=new BufferedWriter(esc);
                for(int r=0;r<columnas.length;r++){
                    bf.write(columnas[r]+";");
                }
                bf.newLine();
                for(int i=0;i<tabla.getRowCount();i++){
                    for(int j=0;j<tabla.getColumnCount();j++){
                        Object o=tabla.getValueAt(i, j);
                        if(o!=null){
                            bf.write((String)o+";");
                        }else{
                            bf.write(";");
                        }
                    }
                    bf.newLine();
                }
                bf.close();
                esc.close();
                JOptionPane.showMessageDialog(null, archivo+" Se ha guardado exitosamente");
            } catch (IOException ex) {
                Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
        
        
        //Guardar como
    }//GEN-LAST:event_btnguardarcomoActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        // TODO add your handling code here:
        //  play
        // jTabbedPane2.setSelectedIndex(1);
    //  Dibujo di=new Dibujo();
      //di.setVisible(true);
        //PLAY
     Dibujo_Server dibujoserver=new Dibujo_Server();
    
        dibujoserver.setVisible(true);
        
       
        
        
        
      
    }//GEN-LAST:event_btnplayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*for(String e:server){
            if(e!=null)
            System.out.println(e);
        }*/
      /*  for(int i=0;i<server.length;i++){
            if(server[i]!=null){
                String[] coo=server[i].split(";");
                double q=Double.parseDouble(coo[2]);
                double q2=Double.parseDouble(coo[3]);
                double q3=Double.parseDouble(coo[4]);
                double q4=Double.parseDouble(coo[5]);
                System.out.println(q+" "+q2+" "+q3+" "+q4+" ");
            }
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // jTabbedPane2.setSelectedIndex(1);
       //Servidor [] ser2=new Servidor[3];
              //JPanel pa=new JPanel();
       //boolean as=false;
     /*   Dibujo di=new Dibujo();
       for(int i=0;i<server.length;i++){
           String aux=server[i];
           if(aux!=null){
                 String[] coo=aux.split(";");
                 di=new Dibujo(
                  coo[2],coo[3],coo[4],coo[5]);*/
     
     
                    //jTabbedPane2.setSelectedIndex(jTabbedPane2.indexOfTab("tab2"));
                    //jTabbedPane2.add(ser);
                    //jTabbedPane2.add(ser, 1);
                    //jPanel3.add(ser);
        //    paneldi.add(ser2[i]);
                    //pa.add(ser2[i])
                   // pa.add(ser2[0]);
                  // paneldi.add(ser2[i]);
               // jTabbedPane2.addTab("Dibujo", ser);
              /*  jTabbedPane2.addTab("Dibujo", ser);
                */ 
              //jTabbedPane2.setSelectedIndex(jTabbedPane2.indexOfTab("Dibujo"));
              
       //    }
  
     // }
   //  di.setVisible(true);     
      //  jTabbedPane2.add(ser);
     
    /*for(Servidor e:ser2){
        paneldi.add(e);  
      } */
      
      
        
       
        //add(ser);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //borrar desde aca
        servidor.imprimir();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        persona.imprimirper();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Texto;
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardarcomo;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnresultados;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnstop;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel paneldi;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
